# Generated by Django 4.2.16 on 2024-11-10 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("full_name", models.CharField(blank=True, max_length=60)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("joining_date", models.DateField(default=django.utils.timezone.now)),
                ("joining_time", models.TimeField(default=django.utils.timezone.now)),
                ("phone", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complaint_id",
                    models.CharField(blank=True, max_length=8, unique=True),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[("pothole", "Pothole"), ("crack", "Crack")],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("location", models.CharField(default="Mehsana", max_length=100)),
                ("coordinates", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="reports/images/")),
                ("google_drive_url", models.URLField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in-progress", "In-Progress"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
