# Generated by Django 4.2.16 on 2024-11-11 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_employee_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="phone_no",
            new_name="phone",
        ),
    ]
