# Generated by Django 4.2.16 on 2024-11-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_employee_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
