# Generated by Django 4.2.16 on 2024-11-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_employee_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="resolved_on",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
