# Generated by Django 4.2.16 on 2024-11-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_complaint_resolved_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
