# Generated by Django 4.2.16 on 2024-11-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_complaint_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="resolved_on",
            field=models.DateTimeField(blank=True),
        ),
    ]
