# Generated by Django 4.2.16 on 2024-12-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_complaint_resolved_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="reports/images/"),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="resolved_on",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
