# Generated by Django 4.2.16 on 2024-12-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_complaint_image_alter_complaint_resolved_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="image",
            field=models.ImageField(upload_to="reports/images/"),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="resolved_on",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
