# Generated by Django 4.2.16 on 2024-12-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_alter_systemsettings_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemsettings",
            options={},
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="setting_name",
            field=models.CharField(max_length=50),
        ),
    ]
